# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"
install: pip install coveralls
script: coverage run --source=valideero setup.py test
after_success: coveralls

